### ISSUE TITLE
大佬，遇到视频任务点，程序提示“不是作业”，然后跳过了

### ISSUE THREAD

**Issue by 19819068211** [uncle-light/chaoxing#1]
![image](https://user-images.githubusercontent.com/66981884/183047199-8cb4d78b-da74-4b69-a023-8b5268a8cd09.png)

**Comment by uncle-light** [comment]
> ![image](https://user-images.githubusercontent.com/66981884/183047199-8cb4d78b-da74-4b69-a023-8b5268a8cd09.png)

已经修复 下载最新发行版就行

**Comment by 19819068211** [comment]
太厉害了，谢谢
