### ISSUE TITLE
请问出现如图情况应该如何处理，如何设置测验强制提交

### ISSUE THREAD

**Issue by 19819068211** [uncle-light/chaoxing#4]
![image](https://user-images.githubusercontent.com/66981884/188306390-f6a1f816-59da-480b-a29f-f4c0544a201e.png)
请问出现如图情况应该如何处理，如何设置测验强制提交，谢谢

**Comment by uncle-light** [comment]
可能是由于课程的原因 具体信息可加tg群反馈
